version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8888:8888"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis  # Reference to the Redis service name (internal Docker network)
    volumes:
      - ./src:/app/src
    restart: always  # Restart container on crash

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:80"
    environment:
      - VITE_WEBSOCKET_URL=${VITE_WEBSOCKET_URL}
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
    restart: always  # Ensure frontend container restarts if it fails

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always  # Restart Redis on crash
    
