# Use an official Python runtime as a parent image
FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /app

# Copy requirements.txt and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application source code
COPY src/ ./src/

# Expose the port that your Tornado server listens on
EXPOSE 8888

# Set the default command to run the Tornado server
CMD ["python", "src/server.py"]
