name: Deploy to EC2

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          VITE_WEBSOCKET_URL: ${{ secrets.VITE_WEBSOCKET_URL }}
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@$EC2_HOST <<EOF
            # Navigate to the project directory
            cd /home/ubuntu/LiquidDuck
            
            # Create .env file with the environment variable
            echo "VITE_WEBSOCKET_URL=${VITE_WEBSOCKET_URL}" > .env
            
            # Pull the latest code
            git pull origin develop
            
            # Stop running containers
            sudo docker-compose down
            
            # Build frontend with environment variable
            cd frontend
            echo "VITE_WEBSOCKET_URL=${VITE_WEBSOCKET_URL}" > .env
            sudo npm install
            sudo npm run build
            cd ..
            
            # Rebuild and start containers
            sudo docker-compose build --no-cache
            sudo docker-compose up -d
            
            # Cleanup
            sudo docker system prune -af
          EOF