name: Deploy to EC2

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Debug environment variables
        run: |
          echo "VITE_WEBSOCKET_URL=${{ secrets.VITE_WEBSOCKET_URL }}"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          VITE_WEBSOCKET_URL: ${{ secrets.VITE_WEBSOCKET_URL }}  # Passing the SERVER_URL from secrets
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@$EC2_HOST <<EOF
            # Navigate to the project directory
            cd /home/ubuntu/LiquidDuck
            
            # Pull the latest code from the Git repository
            git pull origin develop
            
            # Bring down any running containers
            sudo docker-compose down
            
            # Pull the latest Docker images
            sudo docker-compose pull
            
            # Rebuilding the Frontend
            cd frontend
            VITE_WEBSOCKET_URL=${VITE_WEBSOCKET_URL} sudo npm install
            VITE_WEBSOCKET_URL=${VITE_WEBSOCKET_URL} sudo npm run build
            cd ..

            # Rebuild the containers with the latest code and no cache
            VITE_WEBSOCKET_URL=${VITE_WEBSOCKET_URL} sudo docker-compose build --no-cache
            
            # Start the updated containers
            VITE_WEBSOCKET_URL=${VITE_WEBSOCKET_URL} sudo docker-compose up -d --build
            
            # Clean up unused Docker resources
            sudo docker system prune -af
          EOF